// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/Format-C-eft/check-certs/internal/app"
)

// Injectors from wire.go:

func Initialize(contextContext context.Context) (*app.Store, error) {
	store, err := newVaultStore()
	if err != nil {
		return nil, err
	}
	store2 := newAppStore(store)
	return store2, nil
}
